sudo: required
language: generic
services:
  - docker

  before_install:
    - docker build -t amsingh21/docker-react -f Dockerfile.dev . 
    

script:
  - docker run amsingh21/docker-react npm run test -- --coverage